---
##########################################################################################
config_name: Unable to download saved alarm file from Alarm Routing
config_type: app # the program can run the functions defined in this file
###########################################################################################
functions:
- func_name: JBOSS Debug
  JBoss_servers:
  - loggers: [ com.ericsson.oss.services.fm.alarmroutingservice ]
    instances: [ fmhistory ]

  - loggers: [ com.ericsson.oss.services.fm.alarmrouting ]
    instances: [ dlms ]
  timeout: 300
  log_file_paths: [ /ericsson/3pp/jboss/standalone/log/server.log ]
  Jboss_commands:
    - run_commands: true
    - commands: tcpdump -i any -w
