---

config_name: SECURITY
config_type: app

functions:

- func_name: JBOSS Debug
  JBoss_servers:
  - loggers: [ com.ericsson ]
    instances: [ sso,pkiraserv,sps ]
  timeout: 600
  log_file_paths:
  - /ericsson/3pp/jboss/standalone/log/server.log
  Jboss_commands:
    - run_commands: true
    - commands: tcpdump -i any -w

- func_name: Files
  server_type: vm
  instances: [ sso ]
  files: [ /opt/ericsson/sso/heimdallr/opends/logs/errors,/opt/ericsson/sso/heimdallr/opends/logs/access,/opt/ericsson/sso/heimdallr/opends/logs/replication,/var/log/sso/ ]

- func_name: Files
  server_type: vm
  instances: [ httpd ]
  files: [ /var/log/httpd/error_log,/var/log/httpd/access_log ]

- func_name: Files
  server_type: localhost
  files: [ /var/log/enminst.log,/etc/enm-version,/etc/enm-history ]

- func_name: Files
  server_type: peer servers
  instances: [ all_clusters ]
  files: [ /var/log/messages ]

- func_name: Cp From Old Image
  instances: [ svc_cluster ]
  vm_list: [ sso ]
  log_path: [ /ericsson/3pp/jboss/standalone/log/server.log,/var/log/messages,/opt/ericsson/sso/heimdallr/,/var/log/sso/ ]
  image_age: 1

- func_name: Cp From Old Image
  instances: [ svc_cluster ]
  vm_list: [ httpd ]
  log_path: [ /var/log/httpd/error_log,/var/log/httpd/access_log,/var/log/messages ]
  image_age: 1
